# Generated by Django 3.2 on 2021-05-06 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='users',
            new_name='user',
        ),
    ]
